---
- name: Discover latest version of code-server
  ansible.builtin.set_fact:
    version: "{{ (lookup('url', 'https://api.github.com/repos/coder/code-server/releases/latest', headers=_github_api_headers, split_lines=False) | from_json).get('tag_name')
      | replace('v', '') }}"
  run_once: true
  until: version is version('0.0.0', '>=')
  retries: 10
  when: version == "latest"

- name: Download New Code-server
  ansible.builtin.get_url:
    url: "{{ codeserver_url }}"
    dest: /tmp/code-server.rpm
    mode: "0440"

- name: Install New Code-server
  ansible.builtin.dnf:
    name: /tmp/code-server.rpm
    state: present
    disable_gpg_check: true

- name: Allow code-server to listen on port 443
  ansible.builtin.command: setcap cap_net_bind_service=+ep /usr/lib/code-server/lib/node

- name: Find all running services
  ansible.builtin.service_facts:

- name: Restart all running code-server to upgrade
  ansible.builtin.systemd:
    name: "{{ item.value.name }}"
    state: restarted
    daemon_reload: true
  when:
    - '"code-server" in item.value.name'
    - item.value.state == "running"
  loop: "{{ ansible_facts.services | dict2items }}"
